### PR TITLE
ML Workflow Refactoring nonstandardcode.py

### LINKED ISSUE #7: Module 2 Assignment 1
Try to apply as much of the principles discussed in the guidelines document and your own prior experience to reformat and refactor the provided script into a version that is production ready and create a PR.

The submitted version should have the following:

An updated README  document on how to install/run your code

An env.yaml which is the conda environment file that records all the required dependencies of your script. The README should talk about how to install your code and run it.

Make your code packageable and installable as a library ([Here is a reference ](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use)to python packaging). Refer this [link ](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) on the recommended project layout (src layout).

Basic tests (can be scripts) to verify correct installation. Again, refer to the section on project layout for where to place these tests.

Create ML workflow scripts:
A script (ingest_data.py)to download and create training and validation datasets. The script should accept the output folder/file path as an user argument.
A script (train.py) to train the model(s). The script should accept arguments for input (dataset) and output folders (model pickles).
A script (score.py) to score the model(s). The script should accept arguments for model folder, dataset folder and any outputs.

NOTES:
For the above scripts, use the argparse module to accept user arguments when running the scripts. Here is a [quick tutorial ](https://docs.python.org/3/howto/argparse.html)on how to use argparse.
Ensure that your scripts generate a log for each script run ([Here is Tiger’s reference ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#logging)with some example code on logging). Support accepting arguments (to your scripts) for the following
specify the log level (e.g. `--log-level DEBUG`)
use a log file or not (e.g. `--log-path <path>`, default case would be to not write logs to a file)
toggle whether or not to write logs to the console (e.g. `--no-console-log`, default case would be to always write logs to console)
When arguments are not specified, use the appropriate folders from the recommended project layout as the defaults (e.g. data, artifacts, logs etc.)
Feel free to use a configuration file for the default arguments. But, the scripts should still override the config file values if explicitly passed by the user.

Add unit tests and functional tests to your library ([Here is a short introduction ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#code-testing)to testing principles and some example code).

Use Sphinx to generate HTML documents for your library ([Here is a short write up ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#documentation)on Sphinx and an example). Note that, at Tiger, we use the [Numpy docstring style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). Pls. ensure the docstrings follow the same style.

### PR DESCRIPTION
**Pull request by Sreevathsava-TA**
**Branch & Issue Management:**

- Created an issue for tracking this assignment’s requirements.
- Developed a new branch off of the v0.2 tag for these changes, following the naming conventions established in the Git practices module.

**Package Structure:**

- Reorganized files into a src directory, following Python's best practices for project structure.
- Configured the project to be installable as a library, enabling streamlined importing and usage.

**Modularized ML Workflow Scripts:**

- ingest_data.py: Downloads and creates training/validation datasets, accepts the output folder/file path as an argument.
- train.py: Trains models using specified dataset and saves to the output folder.
- score.py: Scores models, with arguments for model folder, dataset folder, and output specifications.
- Each script leverages argparse for robust command-line argument parsing, ensuring flexibility in input handling.

**Logging Enhancements:**

- Integrated comprehensive logging for each script with options for:
- Log level (e.g., --log-level DEBUG)
- Specifying a log file path (e.g., --log-path <path>)
- Console logging toggle (e.g., --no-console-log)
- Default logging paths align with the recommended project layout (data, logs, etc.), with optional configuration overrides.

**Testing:**

- Added basic installation tests to verify correct setup.
- Implemented both unit tests and functional tests for script components, ensuring robustness and alignment with testing principles.
- Positioned tests within the tests directory, adhering to the project layout guide.

**Documentation with Sphinx:**

- Generated HTML documentation using Sphinx, conforming to Tiger’s Numpy docstring style.
- Provided a docs directory with detailed module and function documentation.
Closes #7

### CODE REVIEW

**Review by akashkumar-sharm — CHANGES_REQUESTED** [review]
Do not push build folder in github. inlude this in gitignore.

**Review by akashkumar-sharm — CHANGES_REQUESTED** [review]
The readme file is missing which tells how to run your code. also how to test your codes steps should be mentioned in readme.
steps to generate sphinx build

**Review by akashkumar-sharm — CHANGES_REQUESTED** [review]
Note: Anything that can be generate by your code, should not be pushed to github and should be put in gitignore for example: pkl files, egg info files, any temporary file, datasets, build file. You can google these things. Also once you include it in gitignore delete it from the branch.

**Comment by Sreevathsava-TA** [comment]
> Note: Anything that can be generate by your code, should not be pushed to github and should be put in gitignore for example: pkl files, egg info files, any temporary file, datasets, build file. You can google these things. Also once you include it in gitignore delete it from the branch.

Hi Akash, Do I have to delete the build folder containing html files which is in docs

**Comment by akashkumar-sharm** [comment]
> > Note: Anything that can be generate by your code, should not be pushed to github and should be put in gitignore for example: pkl files, egg info files, any temporary file, datasets, build file. You can google these things. Also once you include it in gitignore delete it from the branch.
> 
> Hi Akash, Do I have to delete the build folder containing html files which is in docs

Yes delete it from github,  but keep it in your local. I can regenerate build file in my system.

**Comment by Sreevathsava-TA** [comment]
> > > Note: Anything that can be generate by your code, should not be pushed to github and should be put in gitignore for example: pkl files, egg info files, any temporary file, datasets, build file. You can google these things. Also once you include it in gitignore delete it from the branch.
> > 
> > 
> > Hi Akash, Do I have to delete the build folder containing html files which is in docs
> 
> Yes delete it from github, but keep it in your local. I can regenerate build file in my system.

Okay Akash I have deleted the files that can be generated from my code

**Review by akashkumar-sharm — CHANGES_REQUESTED** [review]
- The yaml file hasn't updated with new libraries (like sphinx, pytest, etc.) even though you must have installed those package for this assignment.
- The README has some instructions meant for developers only, not end users. Users only need steps like `make html` and `make clean`, not `sphinx quickstart` or `make docs`.
- Missing steps in the README:
     - How to set up a virtual environment.
     - How to install your package.
     - Explain how users can give arguments when running scripts. For example, in the `ingest_data` script, data is saved in the data folder by default, but users can choose a different folder (like xyz).

- `nonstandarcode.py` isn’t needed anymore. If you still want to keep it, move it to a scripts folder.

- `.rst` files are missing in the docs/source folder. These files are needed to create the build folder and generate HTML files for documentation.

**Comment by Sreevathsava-TA** [comment]
> * The yaml file hasn't updated with new libraries (like sphinx, pytest, etc.) even though you must have installed those package for this assignment.
> * The README has some instructions meant for developers only, not end users. Users only need steps like `make html` and `make clean`, not `sphinx quickstart` or `make docs`.
> * Missing steps in the README:
>   
>   * How to set up a virtual environment.
>   * How to install your package.
>   * Explain how users can give arguments when running scripts. For example, in the `ingest_data` script, data is saved in the data folder by default, but users can choose a different folder (like xyz).
> * `nonstandarcode.py` isn’t needed anymore. If you still want to keep it, move it to a scripts folder.
> * `.rst` files are missing in the docs/source folder. These files are needed to create the build folder and generate HTML files for documentation.

Hi Akash,
I have implemented the changes.

**Review by akashkumar-sharm — APPROVED** [review]

**Pull request merged**
